name: Release

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install plugins
        run: |
          npm install \
            @semantic-release/git \
            @semantic-release/changelog \
            @semantic-release/exec \
            conventional-changelog-conventionalcommits

      - name: Configuration
        run: |
          # Setup Semantic Release configuration
          if [ -f ".releaserc" ]; then
            echo "File .releaserc exists"
          else
            cat <<EOT >> .releaserc
          {
            "branches": ["main"],
            "tagFormat": "prodrelease-v${version}",
            "plugins": [
              ["@semantic-release/commit-analyzer"],
              ["@semantic-release/release-notes-generator"],
              [
                "@semantic-release/github",
                {
                  "releaseName": "prodrelease-v${nextRelease.version}"
                }
              ],
              [
                "@semantic-release/git",
                {
                  "assets": ["package.json"],
                  "message": "chore(release): prodrelease-v${nextRelease.version} [skip ci]"
                }
              ]
            ]
          }
          EOT
          echo "Default .releaserc created"
          fi

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
